services:
    tabby:
        build: .
        restart: always
        depends_on:
        - db
        ports:
        - 9090:80
        environment:
        - DATABASE_URL=mysql://root:VERY_GOOD_PASSWORD/tabby
        - PORT=80
        - SOCIAL_AUTH_GITHUB_KEY=YOUR_OWN_KEY
        - SOCIAL_AUTH_GITHUB_SECRET=YOUR_OWN_SECRET
        - DEBUG=False
        - DOCKERIZE_ARGS="-wait tcp://db:3306 -timeout 60s"
         - APP_DIST_STORAGE="file:/mnt/tabby"

    db:
        image: mariadb:10.7.1
        restart: always
        environment:
            MARIADB_DATABASE: tabby
            MARIADB_USER: tabby_user
            MARIADB_PASSWORD: "GOOD_PASSWORD"
            MYSQL_ROOT_PASSWORD: "VERY_GOOD_PASSWORD"